### ISSUE TITLE
Transactional을 직접구현하신 이유가 무엇인가요? 

### ISSUE THREAD

**Issue by rookedsysc** [Sujin1135/layered-architecture#1]
[code](https://github.com/Sujin1135/layered-architecture/blob/main/domain/src/main/kotlin/org/mango/data/service/DomainOrderService.kt#L18C31-L30C30)에 보면 트랜잭셔널을 직접구현하고 계시는데 혹시 @Transactional Annotation을 사용하지 않으신 이유가 무엇인가요?

```kt
@Service
class DomainOrderService(
    private val repository: OrderRepository,
    transactionManager: ReactiveTransactionManager,
) : OrderService {
    private val transactionalOperator = TransactionalOperator.create(transactionManager)

    ... 

    override suspend fun addOrderItem(
        id: UUID,
        orderItem: OrderItem,
    ) {
        transactionalOperator.executeAndAwait {
            val order = getOrder(id)
            order.addOrder(orderItem)

            repository.save(order)
        }
    }

    ... 
}
```

**Comment by Sujin1135** [comment]
안녕하세요 @rookedsysc 님!

트랜잭션을 직접 구현한것은 아니고 spring-tx를 사용하여 블록 내에서 트랜잭션을 제어했습니다.

addOrderItem 메서드의 현재 로직은 어노테이션을 사용해도 동일하게 원자성이 보장 되지만, 만약 로직 내에 다른 외부 API 호출 동작과 같은 로직들이 섞이게 된다면 해당 로직은 트랜잭션 외부로 분리되어야 합니다.

위와 같은 이유들로 인해 트랜잭션 블럭과 분리되어야 할 로직들이 늘어난다면 어떤 로직은 어노테이션으로 관리하고 어떤 로직은 메서드 블럭 내 위와 같은 labmda block 으로 관리 될텐데, 그래서 해당 프로젝트의 Application Layer 에서는 일관성을 고려하여 트랜잭션을 메서드 블럭 안에서 따로 묶어서 실행하는 기조로 작업하려 했습니다 :)

**Comment by rookedsysc** [comment]
@Sujin1135 답변 감사합니다. 추가적으로 트랜잭션 내부에서 외부 API를 호출해야 하는 상황이 어떤 상황인지 알 수 있을까요?

**Comment by Sujin1135** [comment]
@rookedsysc 트랜잭션 내부에서 외부 API를 호출해야 하는 상황은 없고, 하나의 메서드 내에 DB 트랜잭션으로 묶여야 할 부분과 외부 API를 호출해야 하는 부분이 생긴다면 외부 API 호출부는 트랜잭션 로직과는 분리 되어야 합니다 :)

혹시 말씀주셨던 내용이 제가 이해한 내용과 다르다면 다시 한번 말씀주세요!

**Comment by rookedsysc** [comment]
@Sujin1135 외부 API 호출하는 부분이 동일 메서드 내에서 발생해야만 하는 상황이 어떤 상황인지 잘 모르겠다는 얘기였는데 제가 전달을 잘못드린 것 같습니다! 

만약 Annotation을 사용한다면

Facade 메서드를 두고 

```java
val order = getOrder(id) // getOrder에 Transactional 적용
val paymentState = getPaymentState(paymentId)
val order = setOrderState(OrderState.SUCCESS) // Transactional 적용
```

이렇게 코딩해도 되지 않을까 해서 여쭤본 것입니다!

**Comment by Sujin1135** [comment]
@rookedsysc private method 로 각각 로직 단위로 method extraction 하여 제안주신 방법대로 구현을 할 수도 있을것 같습니다 :)

하지만 그렇게 된다면 간단한 단일 로직이 있는 메서드들 조차 presentation 에서 호출할 public 메서드와 transaction 용 private 메서드를 무조건 2개씩 생성해야 할 것 같다는 생각이 듭니다, public 메서드에 transaction을 걸었다가 만약 외부 API 호출할 여건이 생기면 그때 method extraction 해도 되겠지만 처음부터 메서드 블럭 내에서 transaction 블럭을 따로 호출하여 이런 고민을 애초에 없애고 간단하게 일관성을 유지하는 방법을 택했습니다 :)

제안주신 방법도 트랜잭션을 관리하는데 문제가 없기 때문에 좋은 방향이라 생각됩니다!

**Comment by rookedsysc** [comment]
@Sujin1135 제가 의문점이 들었던 부분이 다 해소가 되었습니다. 상세하게 답변주셔서 너무 감사합니다!

**Comment by Sujin1135** [comment]
@rookedsysc 저야말로 해당 프로젝트에 관심을 가져주셔서 정말 감사합니다 :)
